# Generated by Django 4.1.5 on 2023-01-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('projector_availability', models.BooleanField(default=False)),
            ],
        ),
    ]
