# Generated by Django 4.1.5 on 2023-01-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_room', '0002_alter_room_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='name',
        ),
    ]
