# Generated by Django 4.1.5 on 2023-01-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_room', '0004_roomreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
