# Generated by Django 4.1.5 on 2023-01-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_room', '0005_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_a_room.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('room_id', 'date')},
        ),
    ]
